version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.14.1

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - app-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - app-
      - run: 
          name: Install Dependencies
          command: yarn install
      - save_cache: # Save node_modules into cache with a checksum of the package.json
          paths:
            - node_modules
          key: app-{{ checksum "package.json" }}